# Generated by Django 2.1.5 on 2019-04-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet_title', models.CharField(max_length=200)),
                ('snippet_content', models.TextField()),
                ('snippet_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
