# Generated by Django 2.1.5 on 2019-04-12 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='snippet_type',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='snippet_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 23, 44, 11, 680239), verbose_name='date published'),
        ),
    ]
