# Generated by Django 2.1.5 on 2019-04-12 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190412_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='snippet_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 23, 48, 58, 978244), verbose_name='date published'),
        ),
    ]
